apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-k8s-game-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-k8s-game
  template:
    metadata:
      labels:
        app: go-k8s-game
    spec:
      containers:
      - name: go-k8s-game
        image: rahulsssg/go-k8s-game:1.0.1
        ports:
        - containerPort: 7076
